services:
  - docker

script:
  - container_id=$(mktemp)
  - docker build -t container_under_test .
  - docker run --detach -p 80:80 container_under_test > "${container_id}"
  - docker logs "$(cat ${container_id})"
  - docker exec "$(cat ${container_id})" env TERM=xterm nginx -v
  - docker exec "$(cat ${container_id})" env TERM=xterm nginx -t
  - docker exec "$(cat ${container_id})" env TERM=xterm php5 -v
  - docker exec "$(cat ${container_id})" env TERM=xterm redis-server --version
  - sleep 10
  - curl http://127.0.0.1/index.html
  - curl http://127.0.0.1/index.php

notifications:
  slack:
    secure: FpSYZlOkPEnaVE2lVZYAzaySDcDOKdvfRF8z5lJwT37CqSWqfeqeeivNtYvl9kmXGsp5sDM/ach+2pVAE/WPH3btwHLY+QwMiK+Ene5gc82ILkNgZcJbFTLM/ASsUW66kNy+SpAySka/LGVLlbO8Q/DZP1vqPZtZJO1J8dCANEoCCzc/amE2UxlnY08y3oY/YGItRZY/nSZnP42k2OVZ1smHXg+R2j9mdzMve2o+Rr1kyVin4cVysQETxsNhmEuVJxOhs/Vz8wmepqXfcvekDzjv3gOrXWMVtohnE96FuPBChGgF7gBkHI1xcE9+dtf7ZzfaFLiieBC//NmIXys/4PxjbnvbhQUrz7kuBQKKDayZWDEcLABl5eGOQl639GAf7UrcSdcU+cWp2jXTWtKmTlOhWYz+DgGUMO9AYp+ArXDawXfXv0S1AookPMEWnJhSPHLk1VsXOXb/jT17VrL5odM9ML14VQAufUA6n2jRDnjGUc3Gjri4QHvMVD70kqI1zvslsrRigtnxn0K6KfZjYclkGWmR6EYCktG3XCCLDm8wfxLbbmzc+k2dVyvRy6HVeYAkzeUCDyJ31ufNK9A6WmwdaP5FUQaU+ogXcTh38ahgyzyWQNRY2Nf4wlTFrSor5Fz9aUEMwc/RQ1PFEKPrqAbz8XbF3Cj1erBERhs+t5Y=
